# Softmax Regression using Batch Gradient Descent with early stopping from scratch 
  - code for Chapter 4 Exercise problem 11 of Hands-On ml book by A.Geron
  - ps: From scratch dosen't include creation of universe
  - author: Anirudh Reddy

todo
1. get data that you can easily replicate results with sklearn -  iris
2. figure out steps to implement
3. lets do plain logistic reg from scratch to a get a hang of it then go for the softmax
4. logistic reg - setosa or not setosa
    0. init random params
    1. compute X @ parameters - weighted sum
    2. apply sigmoid - logistic
    3. predict labels - y_hat
    4. compute cost function - j(theta) - log loss
    5. compute gradient descent 
    6. update values and go to 4

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
data_iris = load_iris() 
data_iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
#print(data_iris.DESCR)

In [6]:
data_iris.data[0:2], data_iris.target[0:2]

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2]]),
 array([0, 0]))

In [7]:
df = pd.DataFrame(data_iris.data,columns=['a','b','c','d'])
df['e'] = 1
df.head(10)

a    b    c    d  e
0  5.1  3.5  1.4  0.2  1
1  4.9  3.0  1.4  0.2  1
2  4.7  3.2  1.3  0.2  1
3  4.6  3.1  1.5  0.2  1
4  5.0  3.6  1.4  0.2  1
5  5.4  3.9  1.7  0.4  1
6  4.6  3.4  1.4  0.3  1
7  5.0  3.4  1.5  0.2  1
8  4.4  2.9  1.4  0.2  1
9  4.9  3.1  1.5  0.1  1

In [8]:
#X = data_iris.data
X = df.values
y= [0 if x == 0 else 1 for x in data_iris.target ]

In [9]:
theta = np.random.rand(5,1)
theta

array([[0.52740174],
       [0.32508009],
       [0.38564316],
       [0.38394666],
       [0.83285659]])

In [10]:
X[0]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [11]:
ws = X@ theta
ws

array([[5.27707555],
       [5.00905516],
       [4.93002651],
       [4.92190696],
       [5.25684338],
       [5.75781039],
       [5.01926133],
       [5.23039168],
       [4.71284628],
       [5.04173281],
       [5.53887641],
       [5.16347565],
       [4.91792032],
       [4.5385265 ],
       [5.73166818],
       [6.00144232],
       [5.60355312],
       [5.31547021],
       [5.84512824],
       [5.45155856],
       [5.51848101],
       [5.45744521],
       [4.89162542],
       [5.44293648],
       [5.2791686 ],
       [5.13892396],
       [5.34574533],
       [5.36838004],
       [5.29730771],
       [5.04571946],
       [5.06595162],
       [5.51814171],
       [5.52503343],
       [5.71559231],
       [5.08012748],
       [5.04968272],
       [5.44947193],
       [5.16570854],
       [4.70678997],
       [5.28313186],
       [5.22416572],
       [4.57036875],
       [4.77180599],
       [5.45504267],
       [5.64421049],
       [4.99470965],
       [5.45172821],
       [4.915

In [12]:
logit = 1/(1+np.exp(-ws))
logit

array([[0.99491861],
       [0.99336708],
       [0.99282553],
       [0.99276747],
       [0.99481529],
       [0.99685192],
       [0.99343399],
       [0.99467706],
       [0.99110072],
       [0.99357896],
       [0.99608445],
       [0.99431077],
       [0.99273878],
       [0.9894239 ],
       [0.99676881],
       [0.99753093],
       [0.99632878],
       [0.99510907],
       [0.99711439],
       [0.99572871],
       [0.99600409],
       [0.99575367],
       [0.99254676],
       [0.99569188],
       [0.99492918],
       [0.99417019],
       [0.99525423],
       [0.99535995],
       [0.99501987],
       [0.99360434],
       [0.99373163],
       [0.99600274],
       [0.99603009],
       [0.99671662],
       [0.99381932],
       [0.99362948],
       [0.99571982],
       [0.99432339],
       [0.99104715],
       [0.99494913],
       [0.99464399],
       [0.98975197],
       [0.99160598],
       [0.9957435 ],
       [0.99647453],
       [0.99327189],
       [0.99572943],
       [0.992

In [13]:
y_hat_function = lambda x: 1 if x >=.5 else 0
y_hat = [y_hat_function(x) for x in logit ]
y_hat

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [14]:
cost_fn = np.zeros((150,1))
for x in range(len(y_hat)):
    cost_fn[x] = (y_hat[x]* np.log([logit[x]]))+((1-y_hat[x])*np.log([1-logit[x]]))
cost_fn

array([[-5.09434691e-03],
       [-6.65501542e-03],
       [-7.20032703e-03],
       [-7.25881591e-03],
       [-5.19819615e-03],
       [-3.15304281e-03],
       [-6.58766069e-03],
       [-5.33716082e-03],
       [-8.93911078e-03],
       [-6.44174755e-03],
       [-3.92323518e-03],
       [-5.70547100e-03],
       [-7.28770657e-03],
       [-1.06324204e-02],
       [-3.23642217e-03],
       [-2.47212138e-03],
       [-3.67797601e-03],
       [-4.90292810e-03],
       [-2.88978413e-03],
       [-4.28043970e-03],
       [-4.00391104e-03],
       [-4.25536962e-03],
       [-7.48115318e-03],
       [-4.31742566e-03],
       [-5.08372238e-03],
       [-5.84686989e-03],
       [-4.75706307e-03],
       [-4.65084497e-03],
       [-4.99256718e-03],
       [-6.41619977e-03],
       [-6.28809374e-03],
       [-4.00526708e-03],
       [-3.97781346e-03],
       [-3.28878478e-03],
       [-6.19985725e-03],
       [-6.39090196e-03],
       [-4.28936156e-03],
       [-5.69278165e-03],
       [-8.9

In [15]:
sum(-cost_fn)/150

array([0.00230709])

In [16]:
#grad_1 = (logit[0]-y[0])*X[0][0]
grad_1 = sum([(logit[i]-y[i])*X[i][0] for i in range(len(y))])
grad_2 = sum([(logit[i]-y[i])*X[i][1] for i in range(len(y))])
grad_3 = sum([(logit[i]-y[i])*X[i][2] for i in range(len(y))])
grad_4 = sum([(logit[i]-y[i])*X[i][3] for i in range(len(y))])
grad_5 = sum([(logit[i]-y[i])*X[i][4] for i in range(len(y))])
grad_1,grad_2,grad_3,grad_4,grad_5

(array([248.54568571]),
 array([170.29620097]),
 array([72.40638959]),
 array([12.13888976]),
 array([49.65482724]))

In [17]:
lr = 0.01 
theta[0] -= lr*grad_1
theta[1] -= lr*grad_2
theta[2] -= lr*grad_3
theta[3] -= lr*grad_4
theta[4] -= lr*grad_5
theta


array([[-1.95805511],
       [-1.37788192],
       [-0.33842074],
       [ 0.26255776],
       [ 0.33630832]])