In [113]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris

In [123]:
data_iris = load_iris() 
df = pd.DataFrame(data_iris.data,columns=['a','b','c','d'])
df['e'] = 1
X_raw = data_iris.data
X = np.c_[np.ones((150,1)),X_raw]
y= np.array([0 if x == 0 else 1 for x in data_iris.target ])
y=np.reshape(y,(150,1))
obsv = len(y)
params = 5
cost_function_history = []

In [124]:
y.shape

(150, 1)

In [125]:
np.random.seed(42)
theta = np.random.rand(5,1)

In [ ]:
def compute(X,y,theta):
    ws = X@theta
    logit = 1/(1+np.exp(-ws))
    y_hat_function = lambda x: 1 if x >=.7 else 0
    y_hat = [y_hat_function(x) for x in logit ]
    return logit,y_hat


In [178]:
def compute_ws(input_features,weights):
    return input_features@weights
def predict_probability(weighted_sum):
    return 1/(1+np.exp(-weighted_sum))
def predict_class(probability,threshold):
    y_hat_function = lambda x: 1 if x >=threshold else 0
    y_hat = [y_hat_function(x) for x in probability ]
    return y_hat
def cost_function(input_features,weights):
    ws = compute_ws(input_features,weights)
    p = predict_probability(ws)
    cost_function = ((-y.T@np.log(p))+((y-1).T@np.log(1-p)))/obsv
    cost_function_history.append(cost_function)

cost_function(X,theta)
len(cost_function_history)
    

21

In [133]:
def compute_Batch_GradientDescent(input_features,weights,y):
    ws = compute_ws(input_features,weights)
    p = predict_probability(ws)
    gradients = (p-y).T@X
    return gradients
    
    

In [142]:
def update_weights(gradients,learning_rate,weights):
    gradients = np.reshape(gradients,(5,1))
    weights -= learning_rate*gradients
    return weights

In [141]:
grad = compute_Batch_GradientDescent(X,theta,y)
grad

array([[ 49.98659496, 250.23401877, 171.35792458,  73.07610652,
         12.294934  ]])

In [143]:
theta = update_weights(grad,0.01,theta)
theta

array([[-0.12532583],
       [-1.55162588],
       [-0.9815853 ],
       [-0.13210258],
       [ 0.0330693 ]])

In [137]:
X.shape,theta.shape

((150, 5), (5, 1))

In [ ]:
c = np.ones((10,))
c+2

In [144]:
y-1

array([[-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],

In [155]:
ws = compute_ws(X,theta)
p = predict_probability(ws)
y=np.reshape(y,(150,1))
#a=y*np.log(p).T
b=y.T@np.log(p)
a,b,y.T.shape,np.log(p).shape,p.shape
#(p-y).shape,p.shape,y.shape

(array([[ -0.        ,  -0.        ,  -0.        , ...,  -0.        ,
          -0.        ,  -0.        ],
        [ -0.        ,  -0.        ,  -0.        , ...,  -0.        ,
          -0.        ,  -0.        ],
        [ -0.        ,  -0.        ,  -0.        , ...,  -0.        ,
          -0.        ,  -0.        ],
        ...,
        [-11.65250484, -10.85139769, -10.72418195, ..., -13.77644583,
         -13.72009197, -12.83887552],
        [-11.65250484, -10.85139769, -10.72418195, ..., -13.77644583,
         -13.72009197, -12.83887552],
        [-11.65250484, -10.85139769, -10.72418195, ..., -13.77644583,
         -13.72009197, -12.83887552]]),
 array([[-1325.33950636]]),
 (1, 150),
 (150, 1),
 (150, 1))

In [ ]:
cost_list = []
def cost_fn(X,y,theta):
    logit,y_hat = compute(X,y,theta)
    cost_fn = np.zeros((150,1))
    for x in range(obsv):
        cost_fn[x] = (y_hat[x]* np.log([logit[x]]))+((1-y_hat[x])*np.log([1-logit[x]]))
    cost_fn_avg = sum(-cost_fn)/150
    cost_list.append(cost_fn_avg)
    
    

In [ ]:
def bgd(X,y,theta):
    logit,y_hat = compute(X,y,theta)
    grad = np.zeros((5,1))
    for j in range(params):
        grad[j] = sum([(logit[i]-y[i])*X[i][j] for i in range(obsv)])
    return grad


In [ ]:
def update_theta(grad):
    lr = 0.01 
    for i in range(params):
        theta[i] -= lr*grad[i]
    

In [ ]:
epoch = 100
for i in range(epoch):
    cost_fn(X,y,theta)
    grad = bgd(X,y,theta)
    update_theta(grad)
    


In [ ]:
theta

In [ ]:
logit,y_preds = compute(X,y,theta)
logit

In [ ]:
sum(y_preds)